### ISSUE TITLE
Clarification of :setup-function

### ISSUE THREAD

**Issue by Silex** [magit/magit-popup#1]
Hello,

Is `:setup-function` called only once, or each time that the popup is displayed?

My real question is, can I use it as some sort of init system for the popup?

I have a recurring use-case:

``` elisp
(magit-define-popup docker-networks-rm-popup
  "Popup for removing networks."
  'docker-networks-popups
  :man-page "docker-network-rm"
  :actions  '((?D "Remove" docker-networks-rm-selection)))

(advice-add #'docker-networks-rm-popup :before #'docker-utils-select-if-empty)
```

I was wondering if I could hack something like:

``` elisp

(defun hackety-hack (key val)
  (docker-utils-select-if-empty)
  (magit-popup-default-setup key val))

(magit-define-popup docker-networks-rm-popup
  "Popup for removing networks."
  'docker-networks-popups
  :man-page "docker-network-rm"
  :actions  '((?D "Remove" docker-networks-rm-selection))
  :setup-function #'hackety-hack)
```

Of course this raises issues about switching to the correct buffer first, but I think it's neater if you don't see issues with it.

**Comment by tarsius** [comment]
> Is `:setup-function` called only once, or each time that the popup is displayed?

The latter.

> My real question is, can I use it as some sort of init system for the popup?

Yes.

> Of course this raises issues about switching to the correct buffer first, but I think it's neater if you don't see issues with it.

The popup buffer is current when this is called and I am guessing that's what you need. There might be a better (likely undocumented) way to achieve what you want to, but I don't know what is being selected if what is empty :wink:

**Comment by Silex** [comment]
Good news!

> The popup buffer is current when this is called and I am guessing that's what you need. There might be a better (likely undocumented) way to achieve what you want to, but I don't know what is being selected if what is empty

Well actually that's not what I need, but it's ok I can switch to the other buffer temporarily, do my thing and then switch to the popup buffer back. I'll simply use `with-current-buffer`, I have to think a bit about what is the simplest way to find the "original buffer" tho.

Basically I have a `tabulated-list` with entries, and if nothing was selected when the popup appears I'd like to select the entry under the cursor. At the moment I am using a `:before` advice because that was the easiest to code. The idea is to mimic how `ibuffer` works when you press `D` for example.

**Comment by Silex** [comment]
It works! I went with this:

``` elisp
(defun docker-utils-setup-popup (val def)
  (with-current-buffer (other-buffer (current-buffer) 1)
    (docker-utils-select-if-empty))
  (magit-popup-default-setup val def))
```

Thanks :wink:

**Comment by tarsius** [comment]
I just added some new variables that you could use: 70e3cdd6140ebdf477f86b88ac2bd1a8de115e88.

**Comment by Silex** [comment]
Cute, so my snippet above becomes:

``` elisp
(defun docker-utils-setup-popup (val def)
  (magit-with-pre-popup-buffer
    (docker-utils-select-if-empty))
  (magit-popup-default-setup val def))
```
:+1:
