### ISSUE TITLE
Having to restart Emacs for changes in `magit-define-popup` to take effect

### ISSUE THREAD

**Issue by YorkZ** [magit/magit-popup#12]
I'm trying to use `magit-popup` to design my own popup menus (unrelated to `Magit`). However, the problem I've noticed is that each time I change something in `magit-define-popup`, I had to restart Emacs for the changes to take effect. I.e., pressing `C-M-x`, `C-x C-e` or `M-x eval-buffer` won't work. This is very inconvenient, and I really hope the problem could be resolved.

**Comment by tarsius** [comment]
You can use `eval-defun`. I don't know what the default binding for that command is.

**Comment by YorkZ** [comment]
@tarsius Thank you very much. I just tried `M-x eval-defun` but that also didn't work.

**Comment by tarsius** [comment]
Apparently this doesn't work with Emacs 25 but updating to 26 should make it work.

https://github.com/magit/magit/pull/2775

**Comment by YorkZ** [comment]
I'm using Emacs 26.1
I just read your link, and now I see why it doesn't work because the macro uses `defvar`. For me, `eval-defun` had never been able to bind the new value for `defvar`. I'm surprised you believed it worked in Emacs 26. Would you mind trying `eval-defun` on `defvar` again to confirm?

**Comment by tarsius** [comment]
> For me, `eval-defun` had never been able to bind the new value for `defvar`.

Binding the new value for `defvar` is the main reason why that command exists.  From its doc-string:

> > If the current defun is actually a call to `defvar' or `defcustom', evaluating it this way resets the variable using its initial value expression (using the defcustom's :set function if there is one), even if the variable already has some other value.

If that doesn't work for you, then you should investigate why that is so.  Maybe some package that you have installed advises that command in a way that breaks it.  In any case if this doesn't even work for `defvar`, then this clearly is not a `magit-popup` issue.

> I'm surprised you believed it worked in Emacs 26.

Nothing surprising about that.  I have modified popups many times and if this didn't work as expected I would have noticed.

> Would you mind trying `eval-defun` on `defvar` again to confirm?

I did and it still works for me as it always did.

**Comment by YorkZ** [comment]
Turns out that `eval-defun` worked as expected on my system, i.e., running `eval-defun` against `defvar` does reset the variable using its initial value expression even if the variable already has some other value. It is `eval-last-sexp` that never does so, and I was under the wrong impression. My apology for that.

However, the original problem was still there. So the following is an example:

```emacs-lisp
(magit-define-popup test-popup
  "Popup console for test."
  :actions '("Test"
             (?c "test1"
                 (lambda () (interactive) (ignore))))
  :group 'test-group)
```
1. Press `C-M-x` with point inside `magit-define-popup` definition
2. Pressing `C-h v test-popup` gives the following results:
   ```
   test-popup’s value is
   (:variable test-arguments :actions
              ("Test"
               (99 "test1"
                   (lambda nil
                     (interactive)
                     (ignore))))
              :group test-group)

   ```
3. Change `?c "test1"` to `?c "test2"`
4. Press `C-M-x` again with point inside `magit-define-popup` definition
5. Press `C-h v test-popup` still gives the exact same results, i.e., it's still
   `99 "test1"` instead of `99 "test2"`.

Maybe I was doing something wrong?

**Comment by kyleam** [comment]
@YorkZ Are you using lispy?  Using your test case, I can reproduce the issue (with Emacs 26.1) **if I enable lispy**.  I haven't dug any deeper though.

**Comment by YorkZ** [comment]
@kyleam No, I've never used `lispy`. However, `C-h f eval-defun` gives:

```
eval-defun is an interactive compiled Lisp function in
‘elisp-mode.el’.

(eval-defun EDEBUG-IT)

:override advice: ‘edebug-eval-defun’

Evaluate the top-level form containing point, or after point.
...
```
I'm not sure if this advice broke it. `edebug-eval-defun` was defined in `edebug.el` though, but I wasn't able to find anywhere in my customization that explicitly `require edebug`. Do you have any suggestion?

**Comment by kyleam** [comment]
> I'm not sure if this advice broke it. `edebug-eval-defun` was defined in `edebug.el` though, but I wasn't able to find anywhere in my customization that explicitly `require edebug`.

That advice looks to be the same one that I get when I enable lispy, so that should be the culprit.  Any package that requires edebug could then trigger this issue.

Here's a simple demonstration of the issue:

```elisp
(require 'edebug)

(defvar myvar 1)

(defvar myvar 2)

(progn
  (defvar myvar 3))
```

If you call `eval-defun` consecutively on each form, the final value will be 2.  If you drop the `edebug` line, it'll be 3.  I don't have time at the moment to look into the issue any further, but that certainly seems unintentional.  

> Do you have any suggestion?

I'd suggest raising the issue on the Emacs list.
