### ISSUE TITLE
magit-popup presumes `async-bytecomp-allowed-packages` is a list

### ISSUE THREAD

**Issue by gusbrs** [magit/magit-popup#15]
Some recent changes in `async-bytecomp` allow for `async-bytecomp-allowed-packages` to receive the value `'all` (symbol) and no longer `'(all)` list.

`with-editor` has already adapted to this change (https://github.com/jwiegley/emacs-async/issues/117), but `magit-popup` seems to still presume `async-bytecomp-allowed-packages` is always a list at:

```emacs-lisp
(cl-intersection '(all magit)
                 (bound-and-true-p async-bytecomp-allowed-packages))
```
https://github.com/magit/magit-popup/blob/4250c3a606011e3ff2477e3b5bbde2b493f3c85c/magit-popup.el#L51

**Comment by tarsius** [comment]
Thanks for the hint!
