### ISSUE TITLE
Actually ignore .info, .html and .pdf.

### ISSUE THREAD

**Issue by arichiardi** [magit/magit-popup#2]
Hi all :smile: 

I PR-ed `git-modes` as well with this change but I am going to ask a question here because maybe I am misinterpreting.

When I compile the package, I see an `.info` file is generated and the `.gitignore` file actually makes clear that we want to track it:

```
-/magit-popup/
-/magit-popup.html
-/magit-popup.info
-/magit-popup.pdf
```

Why do we want that? This is a bit annoying in cases when I have added `magit-popup` as submodule - in the parent I see a dirty/new files flag. These are generated files so shouldn't we ignore them?

If so, I am going to open a PR with that. If not, well, I can still leave with that and sorry raising the pain :smile: 

Thanks for this and `magit` by the way, they are super!

**Comment by tarsius** [comment]
> Why do we want that?

We don't want that and we also don't do it. It appears you have edited or deleted `.gitignores`. Since the posted lines all begin with `-` I assume this is diff output. Discard your, apparently unintended, changes and things will work as you want to again.
