### ISSUE TITLE
How to have actions with modifiers (CTRL, ALT, etc)

### ISSUE THREAD

**Issue by Silex** [magit/magit-popup#9]
Hello,

Is there a way to bind an action to `C-c o` or other modifiers?

I've tried pretty much everything and it looks like we cannot. Then I saw this

``` elisp
    (define-key map [remap self-insert-command] 'magit-invoke-popup-action)
```

That means there's no way to bind keys with modifiers without modifying `magit-popup-mode-map` right? Which means that I need to create a new mode inheriting from `magit-popup-mode` in order not to pollute all the magit popups.

Just wanted to confirm I understood correctly.

**Comment by tarsius** [comment]
`?\C-CHAR` should work because those are characters too. It won't work out of the gox for other modifiers, but you should be able to use `local-set-key` in `:setup-function`.

**Comment by Silex** [comment]
Fantastic, thanks!

**Comment by YorkZ** [comment]
> `?\C-CHAR` should work because those are characters too. It won't work out of the gox for other modifiers, but you should be able to use `local-set-key` in `:setup-function`.

`?\C-d` doesn't seem to work for me, I'm sure using `local-set-key` in `:setup-function` works, but I really hope I wouldn't have to do that.

**Comment by tarsius** [comment]
I'm afraid you'll have to do just that. Once I have released `magit-popup`'s successor `transient`, you can switch to that. This limitation is one of the things that the latter fixes. (But it currently still lacks some of `magit-popup`'s features, which is why it isn't releases yet.)

**Comment by YorkZ** [comment]
Can't wait for `transient`, when are you going to release it? By the way, thank you so much for `magit-popup`, it's really nice and super useful!
